// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://epbiavrujudxrncpuxcw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVwYmlhdnJ1anVkeHJuY3B1eGN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM1MDU1NDMsImV4cCI6MjA3OTA4MTU0M30.DOBYwsRFI2VRJUlXIeBtk7BmBGgHbMFMpGNMQUaVIAE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});